services:
  instock:
    image: mayanghua/instock:latest
    container_name: InStock
    restart: always
    ports:
      - "9988:9988"
    environment:
      db_host: mysql-container
      db_user: root
      db_password: qloofwYNZGnttbseee
      db_database: instockdb
      db_port: 3306
    volumes:
      - ../.runtime/proxy.txt:/data/InStock/instock/config/proxy.txt
      - ../.runtime/eastmoney_cookie.txt:/data/InStock/instock/config/eastmoney_cookie.txt
    networks:
      - local-net

networks:
  local-net:
    external: true
